// ═══════════════════════════════════════════════════════════════
//  PUBG JORDAN ULTRA PAC v32.0
//  Auto-Generated by Pythonista — 2026-04-27 09:30:51
// ═══════════════════════════════════════════════════════════════
//  IP: 192.168.100.112 | Carrier: UNKNOWN (?)
//  Range: N/A — N/A
//  Network: 5.7 ms DNS | ~4 ms Ping | 3.4 Jitter
//  Grade: S+ (ممتاز جداً) | Score: 86/100
//  Jordan Ranges: 47 (0 for your carrier)
//  Proxies: 2/6 alive
//  Features Enabled:
//     ✅ 🔵 Server Pin — تثبيت سيرفر MENA
//     ✅ 🔒 Lobby Locker — قفل اللوبي
//     ✅ 🕐 Time Awareness — أوقات الذروة
//     ✅ 🌐 DNS Cache — كاش DNS
// ═══════════════════════════════════════════════════════════════


var CFG = {
    NO_DIRECT: true,
    FAIL_CLOSED: true,
    MAX_FB: 3,
    DNS_TTL: 8000,
    DEC_TTL: 2000,
    LOCK_MS: 9000000,
    LIGHT: false,
    MY_CARRIER: "UNKNOWN"
};

var POOL = {
    ORANGE_A: { ip:"46.185.129.122", port:443, carrier:"ORANGE" },
    ORANGE_B: { ip:"46.185.130.44", port:443, carrier:"ORANGE" },
    ZAIN_A: { ip:"79.173.248.71", port:443, carrier:"ZAIN" },
    ZAIN_B: { ip:"176.29.15.200", port:443, carrier:"ZAIN" },
    UMNIAH_A: { ip:"82.212.88.100", port:443, carrier:"UMNIAH" },
    ST_A: { ip:"94.230.12.50", port:443, carrier:"ST" }
};

var B = { D: "DIRECT", X: "PROXY 0.0.0.0:80" };

var MY_CHAIN = ["ORANGE_A", "ZAIN_A", "UMNIAH_A", "ST_A"];


// ═══ JORDAN IPv4 RANGES (47 discovered) ═══
var JO_NETS = [
        ["79.173.248.0", "22", "ZAIN"],
        ["46.185.240.0", "21", "ORANGE"],
        ["79.173.240.0", "21", "ZAIN"],
        ["46.185.128.0", "20", "ORANGE"],
        ["46.185.144.0", "20", "ORANGE"],
        ["46.185.224.0", "20", "ORANGE"],
        ["91.106.224.0", "20", "ORANGE"],
        ["176.29.224.0", "20", "ORANGE"],
        ["176.28.224.0", "20", "ZAIN"],
        ["37.220.224.0", "20", "ZAIN"],
        ["188.247.96.0", "20", "ZAIN"],
        ["46.185.160.0", "19", "ORANGE"],
        ["46.185.192.0", "19", "ORANGE"],
        ["91.106.192.0", "19", "ORANGE"],
        ["176.29.192.0", "19", "ORANGE"],
        ["176.28.192.0", "19", "ZAIN"],
        ["37.220.192.0", "19", "ZAIN"],
        ["188.247.64.0", "19", "ZAIN"],
        ["91.106.128.0", "18", "ORANGE"],
        ["176.29.128.0", "18", "ORANGE"],
        ["79.173.192.0", "18", "ZAIN"],
        ["176.28.128.0", "18", "ZAIN"],
        ["37.220.128.0", "18", "ZAIN"],
        ["188.247.0.0", "18", "ZAIN"],
        ["91.106.0.0", "17", "ORANGE"],
        ["176.29.0.0", "17", "ORANGE"],
        ["176.28.0.0", "17", "ZAIN"],
        ["82.213.224.0", "20", "UMNIAH"],
        ["188.247.224.0", "20", "UMNIAH"],
        ["82.213.192.0", "19", "UMNIAH"],
        ["188.247.192.0", "19", "UMNIAH"],
        ["82.213.128.0", "18", "UMNIAH"],
        ["188.247.128.0", "18", "UMNIAH"],
        ["82.213.0.0", "17", "UMNIAH"],
        ["82.212.0.0", "16", "UMNIAH"],
        ["94.127.216.0", "22", "ST"],
        ["185.49.88.0", "22", "OTHER"],
        ["94.127.208.0", "21", "ST"],
        ["178.20.184.0", "21", "OTHER"],
        ["94.230.224.0", "20", "ST"],
        ["109.237.192.0", "20", "OTHER"],
        ["94.230.192.0", "19", "ST"],
        ["62.72.160.0", "19", "OTHER"],
        ["212.34.0.0", "19", "OTHER"],
        ["94.230.128.0", "18", "ST"],
        ["176.203.0.0", "18", "OTHER"],
        ["94.230.0.0", "17", "ST"]
];

// ═══ CLOUD FOREIGN NETS ═══
var CL_NETS = [
        ["104.16.0.0", "12"],
        ["172.64.0.0", "13"],
        ["162.158.0.0", "15"],
        ["198.41.128.0", "17"],
        ["141.101.64.0", "18"],
        ["108.162.192.0", "18"],
        ["13.224.0.0", "14"],
        ["99.84.0.0", "16"],
        ["3.0.0.0", "8"],
        ["52.84.0.0", "15"],
        ["54.192.0.0", "16"],
        ["151.101.0.0", "16"],
        ["199.232.0.0", "16"],
        ["173.245.48.0", "20"]
];


// ═══ BLOOM FILTER O(1) ═══
var BF={
    b:new Array(1024),
    h1:function(x){var h=0;for(var i=0;i<x.length;i++)h=((h<<5)-h+x.charCodeAt(i))|0;return Math.abs(h)%1024;},
    h2:function(x){var h=5381;for(var i=0;i<x.length;i++)h=((h<<5)+h+x.charCodeAt(i))|0;return Math.abs(h)%1024;},
    h3:function(x){var h=0;for(var i=0;i<x.length;i++)h=(h*31+x.charCodeAt(i))|0;return Math.abs(h)%1024;},
    h4:function(x){var h=17;for(var i=0;i<x.length;i++)h=(h*13+x.charCodeAt(i)*7)|0;return Math.abs(h)%1024;},
    init:function(a){for(var i=0;i<1024;i++)this.b[i]=0;for(var i=0;i<a.length;i++){var l=a[i].toLowerCase();this.b[this.h1(l)]=1;this.b[this.h2(l)]=1;this.b[this.h3(l)]=1;this.b[this.h4(l)]=1;}},
    host:function(h){var p=h.split(/[.\-_]/);for(var i=0;i<p.length;i++)if(p[i].length>=3){var l=p[i].toLowerCase();if(this.b[this.h1(l)]&&this.b[this.h2(l)]&&this.b[this.h3(l)]&&this.b[this.h4(l)])return true;}for(var l=4;l<=Math.min(12,h.length);l++)for(var j=0;j<=h.length-l;j++){var s=h.substr(j,l).toLowerCase();if(this.b[this.h1(s)]&&this.b[this.h2(s)]&&this.b[this.h3(s)]&&this.b[this.h4(s)])return true;}return false;}
};
BF.init(["pubgmobile","pubgm","pubg","tencent","lightspeed","levelinfinite","igamecj","myapp","qq","igame","gcloud","tmgp","bsgame","battlegrounds","proximabeta","garena","pubgstudio"]);


// ═══ FAST IP MATCHER ═══
var IP={
    i2:function(ip){if(!ip)return 0;var p=ip.split(".");if(p.length!==4)return 0;return((parseInt(p[0])<<24)|(parseInt(p[1])<<16)|(parseInt(p[2])<<8)|parseInt(p[3]))>>>0;},
    jo:[],cl:[],
    build:function(){
        var jd=[
        ["79.173.248.0", "22", "ZAIN"],
        ["46.185.240.0", "21", "ORANGE"],
        ["79.173.240.0", "21", "ZAIN"],
        ["46.185.128.0", "20", "ORANGE"],
        ["46.185.144.0", "20", "ORANGE"],
        ["46.185.224.0", "20", "ORANGE"],
        ["91.106.224.0", "20", "ORANGE"],
        ["176.29.224.0", "20", "ORANGE"],
        ["176.28.224.0", "20", "ZAIN"],
        ["37.220.224.0", "20", "ZAIN"],
        ["188.247.96.0", "20", "ZAIN"],
        ["46.185.160.0", "19", "ORANGE"],
        ["46.185.192.0", "19", "ORANGE"],
        ["91.106.192.0", "19", "ORANGE"],
        ["176.29.192.0", "19", "ORANGE"],
        ["176.28.192.0", "19", "ZAIN"],
        ["37.220.192.0", "19", "ZAIN"],
        ["188.247.64.0", "19", "ZAIN"],
        ["91.106.128.0", "18", "ORANGE"],
        ["176.29.128.0", "18", "ORANGE"],
        ["79.173.192.0", "18", "ZAIN"],
        ["176.28.128.0", "18", "ZAIN"],
        ["37.220.128.0", "18", "ZAIN"],
        ["188.247.0.0", "18", "ZAIN"],
        ["91.106.0.0", "17", "ORANGE"],
        ["176.29.0.0", "17", "ORANGE"],
        ["176.28.0.0", "17", "ZAIN"],
        ["82.213.224.0", "20", "UMNIAH"],
        ["188.247.224.0", "20", "UMNIAH"],
        ["82.213.192.0", "19", "UMNIAH"],
        ["188.247.192.0", "19", "UMNIAH"],
        ["82.213.128.0", "18", "UMNIAH"],
        ["188.247.128.0", "18", "UMNIAH"],
        ["82.213.0.0", "17", "UMNIAH"],
        ["82.212.0.0", "16", "UMNIAH"],
        ["94.127.216.0", "22", "ST"],
        ["185.49.88.0", "22", "OTHER"],
        ["94.127.208.0", "21", "ST"],
        ["178.20.184.0", "21", "OTHER"],
        ["94.230.224.0", "20", "ST"],
        ["109.237.192.0", "20", "OTHER"],
        ["94.230.192.0", "19", "ST"],
        ["62.72.160.0", "19", "OTHER"],
        ["212.34.0.0", "19", "OTHER"],
        ["94.230.128.0", "18", "ST"],
        ["176.203.0.0", "18", "OTHER"],
        ["94.230.0.0", "17", "ST"]
        ];
        for(var i=0;i<jd.length;i++){var ip=this.i2(jd[i][0]);var b=parseInt(jd[i][1]);var m=~(0xFFFFFFFF>>>b)>>>0;this.jo.push({n:(ip&m)>>>0,b:(ip|~m)>>>0,c:jd[i][2]});}
        var cd=[
        ["104.16.0.0", "12"],
        ["172.64.0.0", "13"],
        ["162.158.0.0", "15"],
        ["198.41.128.0", "17"],
        ["141.101.64.0", "18"],
        ["108.162.192.0", "18"],
        ["13.224.0.0", "14"],
        ["99.84.0.0", "16"],
        ["3.0.0.0", "8"],
        ["52.84.0.0", "15"],
        ["54.192.0.0", "16"],
        ["151.101.0.0", "16"],
        ["199.232.0.0", "16"],
        ["173.245.48.0", "20"]
        ];
        for(var i=0;i<cd.length;i++){var pts=cd[i].split("/");var ip=this.i2(pts[0]);var b=parseInt(pts[1]);var m=~(0xFFFFFFFF>>>b)>>>0;this.cl.push({n:(ip&m)>>>0,b:(ip|~m)>>>0});}
    },
    isJo:function(ip){var i=this.i2(ip);if(!i)return false;for(var j=0;j<this.jo.length;j++)if(i>=this.jo[j].n&&i<=this.jo[j].b)return true;return false;},
    isCl:function(ip){var i=this.i2(ip);if(!i)return false;for(var j=0;j<this.cl.length;j++)if(i>=this.cl[j].n&&i<=this.cl[j].b)return true;return false;},
    car:function(ip){var i=this.i2(ip);if(!i)return"U";for(var j=0;j<this.jo.length;j++)if(i>=this.jo[j].n&&i<=this.jo[j].b)return this.jo[j].c;return"O";},
    my:function(ip){return this.car(ip)==="UNKNOWN";}
};
IP.build();


// ═══ PING ESTIMATOR ═══
var PE={
    w:0,v:0,t:0,ls:0,on:false,r:new Array(32),rp:0,
    sample:function(d){var p=Math.round(d*0.42+1.5);if(!this.on){this.w=p;this.v=8;this.on=true;}this.w+=0.28*(p-this.w);this.v=0.72*this.v+0.28*Math.abs(p-this.w);this.t=0.12*(p-this.ls)+0.88*this.t;this.ls=p;this.r[this.rp]=p;this.rp=(this.rp+1)%32;return p;},
    p50:function(){var v=[];for(var i=0;i<32;i++)if(this.r[i]!==undefined)v.push(this.r[i]);if(!v.length)return 999;v.sort(function(a,b){return a-b;});return v[Math.floor(v.length/2)];},
    grade:function(){var p=this.p50(),j=Math.round(Math.sqrt(this.v));if(p<=8&&j<=2)return"SS";if(p<=14&&j<=3)return"S+";if(p<=22&&j<=5)return"S";if(p<=35&&j<=8)return"A";if(p<=55)return"B";if(p<=80)return"C";return"D";},
    bad:function(){var g=this.grade();return g==="C"||g==="D";},
    crit:function(){return this.p50()>35||this.p95()>35*2;},
    p95:function(){var v=[];for(var i=0;i<32;i++)if(this.r[i]!==undefined)v.push(this.r[i]);if(!v.length)return 999;v.sort(function(a,b){return a-b;});return v[Math.min(v.length-1,Math.floor(v.length*0.95));},
    jit:function(){return Math.round(Math.sqrt(this.v));}
};

// ═══ SERVER PIN ═══
var SP={
    MENA:["me-","_me","mena","middle_east","arab","jo-","_jo","jordan","amman","gcc","saudi","uae","dubai","egypt","levant","sham","iraq","syria","lebanon","palestine","turkey","tr-"],
    FAR:["eu-","_eu","europe","us-","_us","usa","na-","_na","brazil","br-","_br","asia","sea-","_sea","korea","kr-","_kr","japan","jp-","_jp","china","cn-","_cn","oceania","au-","_au","india","in-","_in","russia","ru-","_ru"],
    score:function(h){var s=0;for(var i=0;i<this.MENA.length;i++)if(h.indexOf(this.MENA[i])!==-1)s+=25;for(var i=0;i<this.FAR.length;i++)if(h.indexOf(this.FAR[i])!==-1)s-=50;return s;},
    far:function(h){return this.score(h)<-20;},
    near:function(h){return this.score(h)>10;}
};

// ═══ ANCHOR ═══
var AN={
    on:false,ch:null,at:0,
    lock:function(c){if(this.on&&!this.exp())return;this.on=true;this.ch=c;this.at=now();},
    get:function(){if(!this.on)return null;if(this.exp()){this.on=false;return null;}return this.ch;},
    exp:function(){return this.on&&(now()-this.at>9000000);},
    renew:function(){if(this.on)this.at=now();}
};

// ═══ SESSION ═══
var SS={
    ph:"IDLE",ch:null,
    phase:function(h,u){
        var c=(h+" "+u).toLowerCase();
        var m=[
            ["G",["game_svr","battle_","sync_","relay_","zone_","bullet_","loot_","vehicle_","player_","damage","kill","knock","revive","airdrop","circle","safe_zone","blue_zone"]],
            ["MM",["matchmake","find_match","queue_","waiting_room","create_room","join_room","countdown","plane_","parachute","warm_up"]],
            ["AU",["oauth","login_","auth_","openid","token_","passport","verify_","anticheat","integrity","security_scan","hwid","device_check"]],
            ["LB",["lobby","shop","store","crate","spin","outfit","skin","emote","friend_","clan_","guild","chat_","invite_","social","profile","rank_","season_","event_","mission","pass_","royal","rp_","badge"]],
            ["PG",["result","reward","exp_","bp_","mvp","play_again","return_lobby","rank_change","tier"]],
            ["UP",["update","patch","hotfix","cdn_","download","resource","apk","obb","version"]]
        ];
        for(var i=0;i<m.length;i++)for(var j=0;j<m[i][1].length;j++)if(c.indexOf(m[i][1][j])!==-1){
            if(m[i][0]!==this.ph){this.ph=m[i][0];if(m[i][0]==="G"||m[i][0]==="MM")AN.lock(this.ch||safeChain(MY_CHAIN));}
            return m[i][0];
        }
        return this.ph;
    }
};

// ═══ TIME ═══
var TM={
    h:function(){return(new Date().getUTCHours()+3)%24;},
    d:function(){return new Date().getUTCDay();},
    peak:function(){var h=this.h();return h>=19&&h<=23;},
    quality:function(){
        if(this.d()===5&&this.peak())return 100;
        if(this.peak())return 90;
        if(this.d()===5)return 80;
        var h=this.h();
        if(h>=16&&h<19)return 70;
        if(h>=0&&h<=3)return 50;
        return 55;
    },
    best:function(){if(this.quality()>=80)return["ORANGE_A","ZAIN_A"];return MY_CHAIN.slice(0,2);}
};

// ═══ DNS + STICKY + HELPERS ═══
var DC={},DK=[];
function dR(h){var e=DC[h];if(e&&now()-e.t<=8000)return e;var t0=now();var ip=dnsResolve(h);var dt=now()-t0;var r={ip:ip,dt:dt,t:now()};if(DK.length>=100){var o=DK.shift();delete DC[o];}DC[h]=r;DK.push(h);PE.sample(dt);return r;}
var SC={};
function sG(k){var e=SC[k];if(!e)return null;if(now()-e.t>300000){delete SC[k];return null;}return e.v;}
function sS(k,v){SC[k]={v:v,t:now()};}
function now(){return(new Date()).getTime();}
function isV4(ip){if(!ip||ip.indexOf(":")!==-1)return false;var p=ip.split(".");if(p.length!==4)return false;for(var i=0;i<4;i++){var n=parseInt(p[i],10);if(isNaN(n)||n<0||n>255)return false;}return true;}
function safeChain(names){var out="",c=0;for(var i=0;i<names.length;i++){var p=POOL[names[i]];if(!p)continue;if(out!=="")out+="; ";out+="PROXY "+p.ip+":"+p.port;c++;if(c>=CFG.MAX_FB)break;}if(out!=="")return out+"; "+B.X;return B.X;}

var BC={},BM=0;


// ═══════════════════════════════════════════════════════════════
//  FindProxyForURL
// ═══════════════════════════════════════════════════════════════

function FindProxyForURL(url,host){
    if(!host)return B.D;
    var h=host.toLowerCase();

    // Local
    if(isPlainHostName(host))return B.D;
    if(isV4(host)){if(isInNet(host,"10.0.0.0","255.0.0.0")||isInNet(host,"172.16.0.0","255.240.0.0")||isInNet(host,"192.168.0.0","255.255.0.0")||isInNet(host,"127.0.0.0","255.0.0.0"))return B.D;}

    // PUBG?
    if(!BF.host(h))return B.D;

    // Cache
    var cc=BC[host];
    if(cc&&now()-cc.t<CFG.DEC_TTL)return cc.p;
    BM++;

    // Anchor
    var lk=AN.get();
    if(lk){BC[host]={p:lk,t:now()};return lk;}

    // Phase
    var ph=SS.phase(host,url);

    // Region Pin
    if(h.indexOf("region")!==-1||h.indexOf("geo")!==-1||h.indexOf("server_list")!==-1||h.indexOf("serverlist")!==-1||h.indexOf("location")!==-1||h.indexOf("locale")!==-1||h.indexOf("device.info")!==-1||h.indexOf("network.info")!==-1){
        var ch=safeChain(["ORANGE_A","ZAIN_A"]);
        AN.lock(ch);BC[host]={p:ch,t:now()};return ch;
    }

    // Telemetry
    if(h.indexOf("analytics")!==-1||h.indexOf("telemetry")!==-1||h.indexOf("tracking")!==-1||h.indexOf("monitor")!==-1||h.indexOf("report")!==-1){
        var ch=safeChain(["ORANGE_A","ZAIN_A"]);
        AN.lock(ch);BC[host]={p:ch,t:now()};return ch;
    }

    // Auth
    if(ph==="AU"){
        var ch=safeChain(["ORANGE_A","ZAIN_A","UMNIAH_A"]);
        AN.lock(ch);BC[host]={p:ch,t:now()};return ch;
    }

    // Lobby
    if(ph==="LB"){
        var sk=sG("LB");
        if(sk){BC[host]={p:sk,t:now()};return sk;}
        var ch=safeChain(MY_CHAIN.slice(0,3));
        sS("LB",ch);SS.ch=ch;BC[host]={p:ch,t:now()};return ch;
    }

    // Matchmaking
    if(ph==="MM"){
        var ch=safeChain(["ORANGE_A","ZAIN_A"]);
        AN.lock(ch);BC[host]={p:ch,t:now()};return ch;
    }

    // In-Game
    if(ph==="G"){
        if(SP.far(h)){var ch=safeChain(["ORANGE_A"]);AN.lock(ch);BC[host]={p:ch,t:now()};return ch;}
        var ch=safeChain(["ORANGE_A"]);
        AN.lock(ch);BC[host]={p:ch,t:now()};return ch;
    }

    // Post-Game
    if(ph==="PG"){
        if(AN.on){BC[host]={p:AN.ch,t:now()};return AN.ch;}
        var ch=safeChain(MY_CHAIN.slice(0,3));
        BC[host]={p:ch,t:now()};return ch;
    }

    // Update
    if(ph==="UP"){
        var ch=safeChain(["ZAIN_A","UMNIAH_A","ORANGE_B","ST_A"]);
        BC[host]={p:ch,t:now()};return ch;
    }

    // DNS
    var dn=dR(host);
    var ip=dn.ip;

    // IP Analysis
    var isJo=false,isCl=false,car="U";
    if(ip&&isV4(ip)){isJo=IP.isJo(ip);isCl=!isJo&&IP.isCl(ip);car=IP.car(ip);}

    // Score
    var sc=0;
    if(isJo)sc+=40;
    if(IP.my(ip))sc+=20;
    if(car==="ORANGE")sc+=15;else if(car==="ZAIN")sc+=13;else if(car==="UMNIAH")sc+=10;
    if(dn.dt<=6)sc+=28;else if(dn.dt<=12)sc+=24;else if(dn.dt<=25)sc+=18;else sc-=5;
    var gr=PE.grade();
    if(gr==="SS")sc+=35;else if(gr==="S+")sc+=30;else if(gr==="S")sc+=25;else if(gr==="A")sc+=18;else sc-=15;
    if(isCl)sc-=15;
    if(SP.near(h))sc+=15;
    if(SP.far(h))sc-=30;
    sc+=Math.round(TM.quality()/10);
    sc=Math.max(0,Math.min(100,sc));

    // Proxy Select
    var proxy;
    if(PE.crit()){proxy=safeChain(["ZAIN_A","ORANGE_A","UMNIAH_A","ST_A"]);}
    else if(sc>=85){var tb=TM.best();proxy=safeChain(tb.slice(0,2));}
    else if(sc>=55){proxy=safeChain(MY_CHAIN.slice(0,3));}
    else{proxy=safeChain(MY_CHAIN);}

    if(SP.far(h))proxy=safeChain(["ORANGE_A"]);
    if(SP.near(h))proxy=safeChain(["ORANGE_A","ZAIN_A"]);

    SS.ch=proxy;
    BC[host]={p:proxy,t:now()};
    if(BM%40===0){for(var k in BC)if(now()-BC[k].t>CFG.DEC_TTL*3)delete BC[k];}
    return proxy;
}
